<a href="https://colab.research.google.com/github/JoaquinGonzalezSimon/Data_science_and_ML_from_Medium/blob/main/220703_Insurance_Prediction_with_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### This project was taken from the following link and I use it to practice my skills

https://thecleverprogrammer.com/2021/09/03/insurance-prediction-with-machine-learning/

https://medium.com/coders-camp/180-data-science-and-machine-learning-projects-with-python-6191bc7b9db9

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('https://raw.githubusercontent.com/amankharwal/Website-data/master/TravelInsurancePrediction.csv')

In [3]:
data.head()

Unnamed: 0  Age               Employment Type GraduateOrNot  AnnualIncome  \
0           0   31             Government Sector           Yes        400000   
1           1   31  Private Sector/Self Employed           Yes       1250000   
2           2   34  Private Sector/Self Employed           Yes        500000   
3           3   28  Private Sector/Self Employed           Yes        700000   
4           4   28  Private Sector/Self Employed           Yes        700000   

   FamilyMembers  ChronicDiseases FrequentFlyer EverTravelledAbroad  \
0              6                1            No                  No   
1              7                0            No                  No   
2              4                1            No                  No   
3              3                1            No                  No   
4              8                1           Yes                  No   

   TravelInsurance  
0                0  
1                0  
2                1  
3                0  
4                0

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1987 entries, 0 to 1986
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   Unnamed: 0           1987 non-null   int64 
 1   Age                  1987 non-null   int64 
 2   Employment Type      1987 non-null   object
 3   GraduateOrNot        1987 non-null   object
 4   AnnualIncome         1987 non-null   int64 
 5   FamilyMembers        1987 non-null   int64 
 6   ChronicDiseases      1987 non-null   int64 
 7   FrequentFlyer        1987 non-null   object
 8   EverTravelledAbroad  1987 non-null   object
 9   TravelInsurance      1987 non-null   int64 
dtypes: int64(6), object(4)
memory usage: 155.4+ KB


In [5]:
data.isnull().sum()

Unnamed: 0             0
Age                    0
Employment Type        0
GraduateOrNot          0
AnnualIncome           0
FamilyMembers          0
ChronicDiseases        0
FrequentFlyer          0
EverTravelledAbroad    0
TravelInsurance        0
dtype: int64

In [6]:
data.drop(columns='Unnamed: 0', inplace=True)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1987 entries, 0 to 1986
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   Age                  1987 non-null   int64 
 1   Employment Type      1987 non-null   object
 2   GraduateOrNot        1987 non-null   object
 3   AnnualIncome         1987 non-null   int64 
 4   FamilyMembers        1987 non-null   int64 
 5   ChronicDiseases      1987 non-null   int64 
 6   FrequentFlyer        1987 non-null   object
 7   EverTravelledAbroad  1987 non-null   object
 8   TravelInsurance      1987 non-null   int64 
dtypes: int64(5), object(4)
memory usage: 139.8+ KB


In [10]:
for i in data.columns:
  print(i)
  print(data[str(i)].unique())
  print('********' * 5)

Age
[31 34 28 25 33 26 32 29 35 30 27]
****************************************
Employment Type
['Government Sector' 'Private Sector/Self Employed']
****************************************
GraduateOrNot
['Yes' 'No']
****************************************
AnnualIncome
[ 400000 1250000  500000  700000 1150000 1300000 1350000 1450000  800000
 1400000  850000 1500000 1050000  350000 1100000  600000  900000  550000
  300000  750000 1200000 1000000  950000 1700000 1750000  650000  450000
 1650000 1800000 1550000]
****************************************
FamilyMembers
[6 7 4 3 8 9 5 2]
****************************************
ChronicDiseases
[1 0]
****************************************
FrequentFlyer
['No' 'Yes']
****************************************
EverTravelledAbroad
['No' 'Yes']
****************************************
TravelInsurance
[0 1]
****************************************


In [11]:
import plotly.express as px

In [17]:
for i in data.columns:
  fig = px.histogram(data, x=i, color='TravelInsurance', title=f'Factors affecting purchase of travel insurance: {i.upper()}', height=500, width=900)
  fig.show()
  print('*****************'*5)

*************************************************************************************


*************************************************************************************


*************************************************************************************


*************************************************************************************


*************************************************************************************


*************************************************************************************


*************************************************************************************


*************************************************************************************


*************************************************************************************


In [20]:
data.EverTravelledAbroad.unique()

array(['No', 'Yes'], dtype=object)

In [21]:
data['GraduateOrNot'] = data['GraduateOrNot'].map({'Yes':1, 'No':0})
data['FrequentFlyer'] = data['FrequentFlyer'].map({'Yes':1, 'No':0})
data['EverTravelledAbroad'] = data['EverTravelledAbroad'].map({'Yes':1, 'No':0})

In [22]:
data.head()

Age               Employment Type  GraduateOrNot  AnnualIncome  \
0   31             Government Sector              1        400000   
1   31  Private Sector/Self Employed              1       1250000   
2   34  Private Sector/Self Employed              1        500000   
3   28  Private Sector/Self Employed              1        700000   
4   28  Private Sector/Self Employed              1        700000   

   FamilyMembers  ChronicDiseases  FrequentFlyer  EverTravelledAbroad  \
0              6                1              0                    0   
1              7                0              0                    0   
2              4                1              0                    0   
3              3                1              0                    0   
4              8                1              1                    0   

   TravelInsurance  
0                0  
1                0  
2                1  
3                0  
4                0

In [23]:
v = np.array(data.drop(columns=['Employment Type','TravelInsurance'], axis=1))
w = np.array(data['TravelInsurance'])

In [24]:
x = np.array(data[["Age", "GraduateOrNot", 
                   "AnnualIncome", "FamilyMembers", 
                   "ChronicDiseases", "FrequentFlyer", 
                   "EverTravelledAbroad"]])
y = np.array(data[["TravelInsurance"]])

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [30]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size=0.10, random_state=42)
xtrain.shape, xtest.shape, ytrain.shape, ytest.shape

((1788, 7), (199, 7), (1788, 1), (199, 1))

In [31]:
vtrain, vtest, wtrain, wtest = train_test_split(v,w, test_size=0.10, random_state=42)
vtrain.shape, vtest.shape, wtrain.shape, wtest.shape

((1788, 7), (199, 7), (1788,), (199,))

In [33]:
modelxy = DecisionTreeClassifier()
modelxy.fit(xtrain, ytrain)
predictions = modelxy.predict(xtest)
print(predictions)
print(predictions.shape)
predictions

[0 1 0 1 1 1 0 0 0 0 1 1 1 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0
 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 0 0 1 1 0 1 1 0 0 0 1 0 0 1 1 0 0 0 0 1
 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0
 0 1 0 1 0 1 1 1 0 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0 1 1 0 0 0 1 1 0 0 1 0 1 0
 1 1 0 0 0 0 0 0 1 0 0 0 0 1]
(199,)


array([0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1])

In [35]:
modelvw = DecisionTreeClassifier()
modelvw.fit(vtrain, wtrain)
ypredictvw = modelvw.predict(vtest)
ypredictvw

array([0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1])

In [37]:
predictions.shape, ytest.shape

((199,), (199, 1))

In [38]:
ypredictvw.shape, wtest.shape

((199,), (199,))

In [39]:
from sklearn import metrics

In [40]:
metrics.accuracy_score(ypredictvw, wtest)

0.8190954773869347

In [41]:
metrics.accuracy_score(predictions, ytest)

0.8241206030150754