<a href="https://colab.research.google.com/github/JoaquinGonzalezSimon/Data_science_and_ML_from_Medium/blob/main/221111_Bitcoin_Price_Prediction_with_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### This project was taken from the following link and I use it to practice my skills

https://thecleverprogrammer.com/2020/05/23/bitcoin-price-prediction-with-machine-learning/

https://medium.com/coders-camp/180-data-science-and-machine-learning-projects-with-python-6191bc7b9db9

In [1]:
pip install yfinance

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 62 kB 952 kB/s 
  Attempting uninstall: requests
    Found existing installation: requests 2.23.0
    Uninstalling requests-2.23.0:
      Successfully uninstalled requests-2.23.0


In [2]:
import pandas as pd
import numpy as np

import yfinance as yf

In [3]:
btc = yf.Ticker('BTC-USD')
btc

yfinance.Ticker object <BTC-USD>

In [4]:
btc.history(period='max')

Open          High           Low  \
Date                                                                  
2014-09-17 00:00:00+00:00    465.864014    468.174011    452.421997   
2014-09-18 00:00:00+00:00    456.859985    456.859985    413.104004   
2014-09-19 00:00:00+00:00    424.102997    427.834991    384.532013   
2014-09-20 00:00:00+00:00    394.673004    423.295990    389.882996   
2014-09-21 00:00:00+00:00    408.084991    412.425995    393.181000   
...                                 ...           ...           ...   
2022-11-07 00:00:00+00:00  20924.621094  21053.246094  20489.972656   
2022-11-08 00:00:00+00:00  20600.671875  20664.607422  17603.544922   
2022-11-09 00:00:00+00:00  18543.761719  18590.458984  15682.692383   
2022-11-10 00:00:00+00:00  15883.158203  18054.312500  15834.018555   
2022-11-11 00:00:00+00:00  17613.328125  17646.191406  16565.859375   

                                  Close        Volume  Dividends  Stock Splits  
Date                                                                            
2014-09-17 00:00:00+00:00    457.334015      21056800          0             0  
2014-09-18 00:00:00+00:00    424.440002      34483200          0             0  
2014-09-19 00:00:00+00:00    394.795990      37919700          0             0  
2014-09-20 00:00:00+00:00    408.903992      36863600          0             0  
2014-09-21 00:00:00+00:00    398.821014      26580100          0             0  
...                                 ...           ...        ...           ...  
2022-11-07 00:00:00+00:00  20602.816406   53510852236          0             0  
2022-11-08 00:00:00+00:00  18541.271484  118992465607          0             0  
2022-11-09 00:00:00+00:00  15880.780273  102905151606          0             0  
2022-11-10 00:00:00+00:00  17586.771484   83202283721          0             0  
2022-11-11 00:00:00+00:00  16694.468750   61361295360          0             0  

[2978 rows x 7 columns]

In [7]:
data = btc.history(period='max')
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2978 entries, 2014-09-17 00:00:00+00:00 to 2022-11-11 00:00:00+00:00
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Open          2978 non-null   float64
 1   High          2978 non-null   float64
 2   Low           2978 non-null   float64
 3   Close         2978 non-null   float64
 4   Volume        2978 non-null   int64  
 5   Dividends     2978 non-null   int64  
 6   Stock Splits  2978 non-null   int64  
dtypes: float64(4), int64(3)
memory usage: 250.7 KB


In [11]:
data.reset_index(drop=False, inplace=True)

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2978 entries, 0 to 2977
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype              
---  ------        --------------  -----              
 0   Date          2978 non-null   datetime64[ns, UTC]
 1   Open          2978 non-null   float64            
 2   High          2978 non-null   float64            
 3   Low           2978 non-null   float64            
 4   Close         2978 non-null   float64            
 5   Volume        2978 non-null   int64              
 6   Dividends     2978 non-null   int64              
 7   Stock Splits  2978 non-null   int64              
dtypes: datetime64[ns, UTC](1), float64(4), int64(3)
memory usage: 186.2 KB


In [14]:
data = data[['Date', 'Close']]

In [18]:
data.drop(columns='Date', inplace=True)

In [19]:
pred_days = 30
data['prediction'] = data['Close'].shift(-pred_days)
data.head()

Close  prediction
0  457.334015  383.757996
1  424.440002  391.441986
2  394.795990  389.545990
3  408.903992  382.845001
4  398.821014  386.475006

In [20]:
data.tail()

Close  prediction
2973  20602.816406         NaN
2974  18541.271484         NaN
2975  15880.780273         NaN
2976  17586.771484         NaN
2977  16702.640625         NaN

In [30]:
x = np.array(data[['Close']])
x = x[:len(data)-pred_days]
x

array([[  457.33401489],
       [  424.44000244],
       [  394.79598999],
       ...,
       [19141.484375  ],
       [19051.41796875],
       [19157.4453125 ]])

In [31]:
y = np.array(data[['prediction']])
y = y[: -pred_days]
y

array([[  383.75799561],
       [  391.44198608],
       [  389.54598999],
       ...,
       [15880.78027344],
       [17586.77148438],
       [16702.640625  ]])

In [32]:
from sklearn.model_selection import train_test_split

In [38]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2)

In [39]:
xtrain.shape, ytrain.shape, xtest.shape, ytest.shape

((2358, 1), (2358, 1), (590, 1), (590, 1))

In [40]:
pred_days_array = np.array(data.drop(['prediction'],1))[-pred_days:]
pred_days_array

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  """Entry point for launching an IPython kernel.


array([[19382.90429688],
       [19185.65625   ],
       [19067.63476562],
       [19268.09375   ],
       [19550.7578125 ],
       [19334.41601562],
       [19139.53515625],
       [19053.74023438],
       [19172.46875   ],
       [19208.18945312],
       [19567.0078125 ],
       [19345.57226562],
       [20095.85742188],
       [20770.44140625],
       [20285.8359375 ],
       [20595.3515625 ],
       [20818.4765625 ],
       [20635.60351562],
       [20495.7734375 ],
       [20485.2734375 ],
       [20159.50390625],
       [20209.98828125],
       [21147.23046875],
       [21282.69140625],
       [20926.48632812],
       [20602.81640625],
       [18541.27148438],
       [15880.78027344],
       [17586.77148438],
       [16702.640625  ]])

In [41]:
from sklearn.svm import SVR

In [42]:
svr_rbf = SVR(kernel='rbf', C=1e3, gamma=0.00001)
svr_rbf.fit(xtrain, ytrain)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1000.0, gamma=1e-05)

In [43]:
svr_rbf_confidence = svr_rbf.score(xtest, ytest)

In [44]:
svr_rbf_confidence

0.7206564985641354

In [46]:
svm_pred = svr_rbf.predict(xtest)
svm_pred

array([ 9144.98647806,   335.84261973, 28841.44188609, 21919.23601623,
       18631.64805344, 20577.20527893, 31805.96286528,  3920.75623217,
       11337.46160033,  8819.81090811,  5250.97395057,  9421.50626225,
        1232.56419424,  8372.69353676,  9129.42958985, 17983.8521629 ,
        3985.97275578,  4210.71658664,   877.61279424, 31502.22682108,
        7567.05010759,   288.24594977,   288.50744821, 29261.34737191,
         295.66787906,  3899.66747266,  4842.33392946,  2750.71538113,
       27240.24688131,  5239.35897165, 27196.6104319 ,  9379.20640262,
       24808.14729093,  9248.91042316,  4051.95942955, 10492.80661488,
       20717.97177899,   352.51143382,   326.04645916, 10763.39081908,
         228.5870289 , 21363.64274466,   197.75792572,   204.67372734,
        1218.54499045,   194.60163733, 10162.63226633,  8116.38045761,
       20273.20884045,  8998.62560095,   771.99481039, 24555.34698272,
         418.86762815,   322.99749257, 25681.03575526,   369.25760882,
      