<a href="https://colab.research.google.com/github/JoaquinGonzalezSimon/Data_science_and_ML_from_Medium/blob/main/221104_Email_Spam_Detection_with_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### This project was taken from the following link and I use it to practice my skills

https://thecleverprogrammer.com/2020/05/17/email-spam-detection-with-machine-learning/

https://medium.com/coders-camp/180-data-science-and-machine-learning-projects-with-python-6191bc7b9db9

In [46]:
import pandas as pd
import numpy as np

import nltk
from nltk.corpus import stopwords
import string

In [47]:
data = pd.read_csv('https://raw.githubusercontent.com/amankharwal/Email-spam-detection/master/emails.csv')

In [48]:
data.head()

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [49]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5728 entries, 0 to 5727
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   text    5728 non-null   object
 1   spam    5728 non-null   int64 
dtypes: int64(1), object(1)
memory usage: 89.6+ KB


In [50]:
data.spam.value_counts()

0    4360
1    1368
Name: spam, dtype: int64

In [51]:
data.spam.value_counts() / data.shape[0]

0    0.761173
1    0.238827
Name: spam, dtype: float64

In [52]:
data[data.duplicated(keep='last')].sort_values(by=['text']).count()

text    33
spam    33
dtype: int64

In [53]:
data.drop_duplicates(inplace=True)

In [54]:
data.spam.value_counts() / data.shape[0]

0    0.759789
1    0.240211
Name: spam, dtype: float64

In [55]:
data.isnull().sum()

text    0
spam    0
dtype: int64

In [56]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [57]:
def process(text):
  no_punc = [char for char in text if char not in string.punctuation]
  no_punc = ''.join(no_punc)

  clean = [word for word in no_punc.split() if word.lower() not in stopwords.words('english')]
  return clean

In [58]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [59]:
no_punc = [char for char in data.text[0] if char not in string.punctuation]

In [60]:
no_punc = ''.join(no_punc)
no_punc

'Subject naturally irresistible your corporate identity  lt is really hard to recollect a company  the  market is full of suqgestions and the information isoverwhelminq  but a good  catchy logo  stylish statlonery and outstanding website  will make the task much easier   we do not promise that havinq ordered a iogo your  company will automaticaily become a world ieader  it isguite ciear that  without good products  effective business organization and practicable aim it  will be hotat nowadays market  but we do promise that your marketing efforts  will become much more effective  here is the list of clear  benefits  creativeness  hand  made  original logos  specially done  to reflect your distinctive company image  convenience  logo and stationery  are provided in all formats  easy  to  use content management system letsyou  change your website content and even its structure  promptness  you  will see logo drafts within three business days  affordability  your  marketing break  through 

In [61]:
clean = [word for word in no_punc.split() if word.lower() not in stopwords.words('english')]
clean

['Subject',
 'naturally',
 'irresistible',
 'corporate',
 'identity',
 'lt',
 'really',
 'hard',
 'recollect',
 'company',
 'market',
 'full',
 'suqgestions',
 'information',
 'isoverwhelminq',
 'good',
 'catchy',
 'logo',
 'stylish',
 'statlonery',
 'outstanding',
 'website',
 'make',
 'task',
 'much',
 'easier',
 'promise',
 'havinq',
 'ordered',
 'iogo',
 'company',
 'automaticaily',
 'become',
 'world',
 'ieader',
 'isguite',
 'ciear',
 'without',
 'good',
 'products',
 'effective',
 'business',
 'organization',
 'practicable',
 'aim',
 'hotat',
 'nowadays',
 'market',
 'promise',
 'marketing',
 'efforts',
 'become',
 'much',
 'effective',
 'list',
 'clear',
 'benefits',
 'creativeness',
 'hand',
 'made',
 'original',
 'logos',
 'specially',
 'done',
 'reflect',
 'distinctive',
 'company',
 'image',
 'convenience',
 'logo',
 'stationery',
 'provided',
 'formats',
 'easy',
 'use',
 'content',
 'management',
 'system',
 'letsyou',
 'change',
 'website',
 'content',
 'even',
 'structu

In [62]:
data['text'].head().apply(process)[0]

['Subject',
 'naturally',
 'irresistible',
 'corporate',
 'identity',
 'lt',
 'really',
 'hard',
 'recollect',
 'company',
 'market',
 'full',
 'suqgestions',
 'information',
 'isoverwhelminq',
 'good',
 'catchy',
 'logo',
 'stylish',
 'statlonery',
 'outstanding',
 'website',
 'make',
 'task',
 'much',
 'easier',
 'promise',
 'havinq',
 'ordered',
 'iogo',
 'company',
 'automaticaily',
 'become',
 'world',
 'ieader',
 'isguite',
 'ciear',
 'without',
 'good',
 'products',
 'effective',
 'business',
 'organization',
 'practicable',
 'aim',
 'hotat',
 'nowadays',
 'market',
 'promise',
 'marketing',
 'efforts',
 'become',
 'much',
 'effective',
 'list',
 'clear',
 'benefits',
 'creativeness',
 'hand',
 'made',
 'original',
 'logos',
 'specially',
 'done',
 'reflect',
 'distinctive',
 'company',
 'image',
 'convenience',
 'logo',
 'stationery',
 'provided',
 'formats',
 'easy',
 'use',
 'content',
 'management',
 'system',
 'letsyou',
 'change',
 'website',
 'content',
 'even',
 'structu

In [63]:
from sklearn.feature_extraction.text import CountVectorizer

In [64]:
message = CountVectorizer(analyzer=process).fit_transform(data['text'])
message

<5695x37229 sparse matrix of type '<class 'numpy.int64'>'
	with 562930 stored elements in Compressed Sparse Row format>

In [65]:
from sklearn.model_selection import train_test_split

In [66]:
xtrain, xtest, ytrain, ytest = train_test_split(message, data['spam'], test_size=0.20)
xtrain, xtest, ytrain, ytest

(<4556x37229 sparse matrix of type '<class 'numpy.int64'>'
 	with 451096 stored elements in Compressed Sparse Row format>,
 <1139x37229 sparse matrix of type '<class 'numpy.int64'>'
 	with 111834 stored elements in Compressed Sparse Row format>,
 4918    0
 143     1
 3206    0
 1507    0
 1787    0
        ..
 5624    0
 1325    1
 5439    0
 3553    0
 1159    1
 Name: spam, Length: 4556, dtype: int64,
 4549    0
 3219    0
 1335    1
 4381    0
 1003    1
        ..
 4343    0
 2953    0
 4608    0
 3385    0
 4036    0
 Name: spam, Length: 1139, dtype: int64)

In [67]:
from sklearn.naive_bayes import MultinomialNB

In [68]:
classifier = MultinomialNB().fit(xtrain, ytrain)
classifier.predict(xtrain)

array([0, 1, 0, ..., 0, 0, 1])

In [69]:
ytrain.values

array([0, 1, 0, ..., 0, 0, 1])

In [71]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [72]:
pred = classifier.predict(xtrain)
print(classification_report(ytrain, pred))
print('--------------------'*2)
print('Confusion matrix: \n', confusion_matrix(ytrain, pred))
print('Accuracy Score: \n', accuracy_score(ytrain, pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3481
           1       0.99      1.00      0.99      1075

    accuracy                           1.00      4556
   macro avg       0.99      1.00      1.00      4556
weighted avg       1.00      1.00      1.00      4556

----------------------------------------
Confusion matrix: 
 [[3468   13]
 [   3 1072]]
Accuracy Score: 
 0.9964881474978051


In [73]:
classifier.predict(xtest)

array([0, 0, 1, ..., 0, 0, 0])

In [74]:
ytest.values

array([0, 0, 1, ..., 0, 0, 0])

In [76]:
pred_test = classifier.predict(xtest)
print(classification_report(ytest, pred_test))
print('--------------------'*2)
print('Confusion matrix: \n', confusion_matrix(ytest, pred_test))
print('--------------------'*2)
print('Accuracy Score: \n', accuracy_score(ytest, pred_test))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       846
           1       0.97      0.99      0.98       293

    accuracy                           0.99      1139
   macro avg       0.98      0.99      0.99      1139
weighted avg       0.99      0.99      0.99      1139

----------------------------------------
Confusion matrix: 
 [[837   9]
 [  2 291]]
----------------------------------------
Accuracy Score: 
 0.990342405618964
